### ISSUE TITLE
relation matching

### ISSUE THREAD

**Issue by lxylxyoo** [malllabiisc/EmbedKGQA#1]
Thanks for opening source !
I have read the code, but I did not find the **relation matching** module. The current prediction logic seems to be predicting scores for all entities of KG.  Will you provide the code for **relation matching**， because I am not sure how is the shortest path between head entity and candidate answer defined.

**Comment by apoorvumang** [comment]
Yes we will provide soon, along with the data and instructions.
Thanks!

**Comment by Hy-Choi** [comment]
@apoorvumang When do you provide data and instructions?

**Comment by IISCAditayTripathi** [comment]
@Hy-Choi @lxylxyoo we have added the data and instructions to perform experiments on MetaQA dataset. We will add the same for WebQSP in a couple of days. Please check out the code and data. Thanks.

**Comment by Hy-Choi** [comment]
@IISCAditayTripathi  OK, Thanks.

**Comment by Kelaxon** [comment]
Hi, @apoorvumang thanks for providing these useful codes and instructions.
I am also trying to implement the relation matching part and have a question regarding pruning candidates (a' \in Nh) in section 4.4.1:
![image](https://user-images.githubusercontent.com/19503195/97102167-4e787500-16de-11eb-813b-12abc859a95e.png)
Here, what is the meaning of `Nh` and how can we obtain it? You mentioned that candidates `a'` could be obtained in section 4.4. However, I see `a'` are all possible answers in section 4.4 (which is not pruned). Hope to get your feedback. Thanks.

**Comment by apoorvumang** [comment]
Hi @Kelaxon 

That is a typo. It should be same as in section 4.4 ie a' \in E. We were earlier experimenting with restricting the neighbourhood, which was denoted by N_h, but the final version of EmbedKGQA does not have that restriction.

**Comment by Kelaxon** [comment]
@apoorvumang Thanks for your reply.

Yes, I found the restricting neighborhood part in `getNeighbourhood()` in folder `RoBERTa`. It has one hyper-parameter `radius`. So, what is the empirical range of it? Besides, according to section 4.4, it actually has two parameters needed to determine: `radius` and `r`(gamma in the paper), right?

**Comment by RainbowRr** [comment]
@apoorvumang When do you provide relation matching code?It's nine months since you said public code last time.I'm very curious about the implementation of relation matching

**Comment by apoorvumang** [comment]
@RainbowRr Apologies, I have been busy with some other work and sidelining this for way too long. Please keep posted on this thread I will add the implementation in some form or another within the next 3 days.

**Comment by RainbowRr** [comment]
> @RainbowRr Apologies, I have been busy with some other work and sidelining this for way too long. Please keep posted on this thread I will add the implementation in some form or another within the next 3 days.

Thank you very much! Wish you success in your work and research!

**Comment by apoorvumang** [comment]
@RainbowRr I have added the code. Please let me know if you face any issues

**Comment by apoorvumang** [comment]
You will need to re-download the data and pretrained_models

**Comment by apoorvumang** [comment]
Closing for new, please reopen a new issue if you have problems with the implementation
