### ISSUE TITLE
Creating model... Downloading:   0%|                                                                                                                                      | 438k/501M [01:00<72:03:39, 1.93kB/s]

### ISSUE THREAD

**Issue by cx51666666** [malllabiisc/EmbedKGQA#100]
Creating model...
Downloading:   0%|                                                                                                                                      | 438k/501M [01:00<72:03:39, 1.93kB/s]

What file do I need to download?  Where else can I download it?  Thank you！

**Comment by apoorvumang** [comment]
can you provide more details about what command you used?

**Comment by cx51666666** [comment]
Thank you for your reply. 
The path is EmbedKGQA/KGQA/RoBERTa.
Command:
~/project/EmbedKGQA/KGQA/RoBERTa$  python3 main.py --mode train --relation_dim 200 --do_batch_norm 1 --gpu 2 --freeze 1 --batch_size 16 --validate_every 10 --hops webqsp_half --lr 0.00002 --entdrop 0.0 --reldrop 0.0 --scoredrop 0.0 --decay 1.0 --model ComplEx --patience 20 --ls 0.05 --l3_reg 0.001 --nb_epochs 200 --outfile half_fbwq

**Comment by apoorvumang** [comment]
What's probably happening is huggingface (transformers library) is trying to download RoBERTa checkpoints + tokenizers. Does it not download for you?

**Comment by cx51666666** [comment]
Due to network reasons, the download speed of the model is very slow, and there will be connection failure.
Where can I download it manually? What path should I put it in after downloading? Thanks！

**Comment by apoorvumang** [comment]
I'm not sure, I think it would be better to refer to Huggingface's documentation for this
