### ISSUE TITLE
Question about "adding 2-hop neighbourhood filtering"

### ISSUE THREAD

**Issue by mug2mag** [malllabiisc/EmbedKGQA#101]
@apoorvumang hi, I am here again. Thanks for your responsible responses to all questions.

I want to make sure if "adding 2-hop neighbourhood filtering" you mentioned in 'Table 5' means that the prediction answer entities will be confined in the 2-hop neighbourhood related to the given topic entity in question at inference?

**Comment by apoorvumang** [comment]
yes
