### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers'

### ISSUE THREAD

**Issue by lihuiliullh** [malllabiisc/EmbedKGQA#107]
Hi, may I know the transformers version in your project? I installed the transformers by running "pip install transformers", but still got the error.

from transformers import *
ModuleNotFoundError: No module named 'transformers'

**Comment by apoorvumang** [comment]
Are you using conda?

**Comment by lihuiliullh** [comment]
I use pip.

**Comment by apoorvumang** [comment]
I think this question would be better answered on stackoverflow, I'm not sure how I can help
