### ISSUE TITLE
TransE

### ISSUE THREAD

**Issue by haipeng123** [malllabiisc/EmbedKGQA#111]
Excuse me, after reading your paper, I don't quite understand that Transe is not suitable for multi hop reasoning. Can you explain it?

**Comment by apoorvumang** [comment]
In TransE, if a vector for a relation is r, then vector for the inverse relation should be -r . So for a multi-hop path such as co-actor which requires path (acted in, acted in inverse), the resulting 2-hop path embedding would become 0 vector. So TransE may not be able to answer such questions.

**Comment by haipeng123** [comment]
> In TransE, if a vector for a relation is r, then vector for the inverse relation should be -r . So for a multi-hop path such as co-actor which requires path (acted in, acted in inverse), the resulting 2-hop path embedding would become 0 vector. So TransE may not be able to answer such questions.

I see what you mean. Thank you for your answer!
