### ISSUE TITLE
replace the pretrained model

### ISSUE THREAD

**Issue by AdienQ** [malllabiisc/EmbedKGQA#113]
Can I replace roberta-base with another pretraining model?
What needs to be modified？

**Comment by AdienQ** [comment]
<img width="957" alt="截屏2021-12-13 下午8 41 41" src="https://user-images.githubusercontent.com/49086157/145814530-a99cb7b4-38fc-44fa-9a92-1298b30e6417.png">
when I changed the pretraining model ,  the following error created:
<img width="1487" alt="截屏2021-12-13 下午8 41 20" src="https://user-images.githubusercontent.com/49086157/145814787-f2d46ef4-3326-4f53-aecd-c94a5414459b.png">

**Comment by apoorvumang** [comment]
You can ignore this warning

**Comment by AdienQ** [comment]
> 

not only the warning, but also the following error:
<img width="1491" alt="截屏2021-12-13 下午8 57 58" src="https://user-images.githubusercontent.com/49086157/145816831-46dd9d05-d639-43ad-abaf-faf8b4033f61.png">

**Comment by AdienQ** [comment]
Is it because of the transformers version？

**Comment by AdienQ** [comment]
> Not sure about this error, it might be due to transformers version. The transformers version used by us is '2.1.1'
> 
> Output of `conda list` (ofc you don't need all these packages)
> 
> ```
> # packages in environment at /scratche/home/apoorv/EmbedKGQA/embedkgqa_env:
> #
> # Name                    Version                   Build  Channel
> _libgcc_mutex             0.1                        main
> attrs                     19.3.0                     py_0
> backcall                  0.1.0                    py37_0
> blas                      1.0                         mkl
> bleach                    3.1.0                    py37_0
> boto3                     1.10.8                     py_0    conda-forge
> botocore                  1.13.8                     py_0    conda-forge
> ca-certificates           2020.10.14                    0
> catalogue                 1.0.0                      py_0    conda-forge
> certifi                   2020.11.8        py37h06a4308_0
> cffi                      1.13.2           py37h2e261b9_0
> chardet                   3.0.4                 py37_1003    conda-forge
> click                     7.0                        py_0    conda-forge
> cryptography              2.8              py37h72c5cf5_0    conda-forge
> cudatoolkit               10.1.243             h6bb024c_0
> cycler                    0.10.0                     py_2    conda-forge
> cymem                     2.0.3            py37he1b5a44_0    conda-forge
> cython-blis               0.4.1            py37h516909a_0    conda-forge
> dbus                      1.13.12              h746ee38_0
> decorator                 4.4.1                      py_0
> defusedxml                0.6.0                      py_0
> docutils                  0.15.2                   py37_0    conda-forge
> entrypoints               0.3                      py37_0
> expat                     2.2.6                he6710b0_0
> fontconfig                2.13.0               h9420a91_0
> freetype                  2.9.1                h8a8886c_1
> glib                      2.63.1               h5a9c865_0
> gmp                       6.1.2                h6c8ec71_1
> gst-plugins-base          1.14.0               hbbd80ab_1
> gstreamer                 1.14.0               hb453b48_1
> icu                       58.2                 h9c2bf20_1
> idna                      2.8                   py37_1000    conda-forge
> importlib_metadata        0.23                     py37_0
> intel-openmp              2019.4                      243
> ipykernel                 5.1.3            py37h39e3cac_0
> ipython                   7.9.0            py37h39e3cac_0
> ipython_genutils          0.2.0                    py37_0
> ipywidgets                7.5.1                      py_0
> jedi                      0.15.1                   py37_0
> jinja2                    2.10.3                     py_0
> jmespath                  0.9.4                      py_0    conda-forge
> joblib                    0.14.0                     py_0
> jpeg                      9b                   h024ee3a_2
> jsonschema                3.1.1                    py37_0
> jupyter                   1.0.0                    py37_7
> jupyter_client            5.3.4                    py37_0
> jupyter_console           6.0.0                    py37_0
> jupyter_core              4.6.1                    py37_0
> kiwisolver                1.2.0            py37h99015e2_0    conda-forge
> libedit                   3.1.20181209         hc058e9b_0
> libffi                    3.2.1                hd88cf55_4
> libgcc-ng                 9.1.0                hdf63c60_0
> libgfortran-ng            7.3.0                hdf63c60_0
> libllvm10                 10.0.1               hbcb73fb_5
> libpng                    1.6.37               hbc83047_0
> libsodium                 1.0.16               h1bed415_0
> libstdcxx-ng              9.1.0                hdf63c60_0
> libtiff                   4.1.0                h2733197_0
> libuuid                   1.0.3                h1bed415_2
> libxcb                    1.13                 h1bed415_1
> libxml2                   2.9.9                hea5a465_1
> llvmlite                  0.34.0           py37h269e1b5_4
> markupsafe                1.1.1            py37h7b6447c_0
> matplotlib                3.1.3                    py37_0
> matplotlib-base           3.1.3            py37hef1b27d_0
> mistune                   0.8.4            py37h7b6447c_0
> mkl                       2019.4                      243
> mkl-service               2.3.0            py37he904b0f_0
> mkl_fft                   1.0.15           py37ha843d7b_0
> mkl_random                1.1.0            py37hd6b4f25_0
> more-itertools            7.2.0                    py37_0
> murmurhash                1.0.0            py37he1b5a44_0    conda-forge
> nbconvert                 5.6.1                    py37_0
> nbformat                  4.4.0                    py37_0
> ncurses                   6.1                  he6710b0_1
> networkx                  2.4                        py_0
> ninja                     1.9.0            py37hfd86e86_0
> notebook                  6.0.2                    py37_0
> numba                     0.51.2           py37h04863e7_1
> numpy                     1.17.3           py37hd14ec0e_0
> numpy-base                1.17.3           py37hde5b4d6_0
> olefile                   0.46                     py37_0
> openssl                   1.1.1h               h7b6447c_0
> pandoc                    2.2.3.2                       0
> pandocfilters             1.4.2                    py37_1
> parso                     0.5.1                      py_0
> path                      16.0.0                   pypi_0    pypi
> path-py                   12.5.0                   pypi_0    pypi
> pcre                      8.43                 he6710b0_0
> pexpect                   4.7.0                    py37_0
> pickleshare               0.7.5                    py37_0
> pillow                    6.2.1            py37h34e0f95_0
> pip                       19.3.1                   py37_0
> plac                      0.9.6                      py_1    conda-forge
> preshed                   3.0.2            py37he1b5a44_1    conda-forge
> prometheus_client         0.7.1                      py_0
> prompt_toolkit            2.0.10                     py_0
> ptyprocess                0.6.0                    py37_0
> pycparser                 2.19                     py37_0
> pygments                  2.4.2                      py_0
> pyopenssl                 19.0.0                   py37_0    conda-forge
> pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
> pyqt                      5.9.2            py37h05f1152_2
> pyrsistent                0.15.5           py37h7b6447c_0
> pysocks                   1.7.1                    py37_0    conda-forge
> python                    3.7.5                h0371630_0
> python-dateutil           2.8.1                      py_0
> python_abi                3.7                     1_cp37m    conda-forge
> pytorch                   1.3.1           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
> pyyaml                    5.3.1                    pypi_0    pypi
> pyzmq                     18.1.0           py37he6710b0_0
> qt                        5.9.7                h5867ecd_1
> qtconsole                 4.5.5                      py_0
> readline                  7.0                  h7b6447c_5
> regex                     2019.11.1        py37h516909a_0    conda-forge
> requests                  2.22.0                   py37_1    conda-forge
> s3transfer                0.2.1                    py37_0    conda-forge
> sacremoses                0.0.35                     py_0    conda-forge
> scikit-learn              0.21.3           py37hd81dba3_0    anaconda
> scipy                     1.3.1            py37h7c811a0_0
> send2trash                1.5.0                    py37_0
> setuptools                41.6.0                   py37_0
> sip                       4.19.8           py37hf484d3e_0
> six                       1.13.0                   py37_0
> spacy                     2.2.3            py37hc9558a2_0    conda-forge
> sqlite                    3.30.1               h7b6447c_0
> srsly                     1.0.0            py37he1b5a44_0    conda-forge
> tbb                       2020.3               hfd86e86_0
> terminado                 0.8.2                    py37_0
> testpath                  0.4.4                      py_0
> thinc                     7.3.0            py37hc9558a2_0    conda-forge
> tk                        8.6.8                hbc83047_0
> torchvision               0.4.2                py37_cu101    pytorch
> tornado                   6.0.3            py37h7b6447c_0
> tqdm                      4.36.1                     py_0
> traitlets                 4.3.3                    py37_0
> transformers              2.1.1                      py_0    conda-forge
> urllib3                   1.25.7                   py37_0    conda-forge
> wasabi                    0.6.0                      py_0    conda-forge
> wcwidth                   0.1.7                    py37_0
> webencodings              0.5.1                    py37_1
> wheel                     0.33.6                   py37_0
> widgetsnbextension        3.5.1                    py37_0
> xz                        5.2.4                h14c3975_4
> yaml                      0.2.5                h7b6447c_0
> zeromq                    4.3.1                he6710b0_3
> zipp                      0.6.0                      py_0
> zlib                      1.2.11               h7b6447c_3
> zstd                      1.3.7                h0b5b093_0
> ```

Thank you very much！
