### ISSUE TITLE
Are 2-hop and 3-hop triple needed to be trained during KGE phrase?

### ISSUE THREAD

**Issue by mug2mag** [malllabiisc/EmbedKGQA#114]
@apoorvumang 

hi, I have a question about the knowledge embedding training:
Are 2-hop and 3-hop triples needed to be trained during KGE phrase? That is triples in fbwq_full datasert likes `(m.0rh6k location.location.people_born_here	m.02qd3hj)` (3-hop triple) and `(m.010bss7d film.genre	m.03k9fj)` (2-hop triple) and `(m.0gkt5x0	country	m.06qd3)` (1-hop triple) are put together to get knowledge embedding by KGE?

Any reply would be appreciated.

**Comment by apoorvumang** [comment]
I'm not sure I understand what you mean by 2/3 hop triples. `location.location.people_born_here` is a single relation in Freebase, not a 3-hop relation path. The reason it looks like 3 relations concatenated together is due to the schema used by freebase , but in reality it is a single relation.

**Comment by mug2mag** [comment]
@apoorvumang 
Thanks for your reply. 

> location.location.people_born_here is a single relation in Freebase, not a 3-hop relation path
So how do you define a 3-hop relation in fbwq_full dataset? And did you regard  `(m.0rh6k location.location.people_born_here m.02qd3hj)`  as training data during KGE training?

Furthermore,  as the published MetaQA dataset shows that there are 1-hop, 2-hop, 3-hop train dataset, dev dataset and test dataset respectively. Did you gather all training data to train one model and test the performance by the one model for these three hops test questions separately?

**Comment by apoorvumang** [comment]
>So how do you define a 3-hop relation in fbwq_full dataset? 

We don't define _relations_ to be 1,2 or 3-hop, we define _questions_ as 1,2, or 3-hops, depending on how many hops of reasoning are required to answer them. Relations are considered atomic.

> And did you regard (m.0rh6k location.location.people_born_here m.02qd3hj) as training data during KGE training?

Not sure about this particular triple, but yes similar looking relations would have been used in KGE training

For MetaQA, we trained KG embeddings once. Then for each QA dataset (1,2 and 3-hop) we train and evaluate the QA model separately

**Comment by mug2mag** [comment]
> For MetaQA, we trained KG embeddings once. Then for each QA dataset (1,2 and 3-hop) we train and evaluate the QA model separately

So in EmbedKGQA stage, you have three trained models?

**Comment by apoorvumang** [comment]
Yes 3 different models for MetaQA

**Comment by mug2mag** [comment]
Thanks very much for your reply and patience!!
