### ISSUE TITLE
[MetaQA] Training data contains knowledge base triplets as questions

### ISSUE THREAD

**Issue by AndreiCComan** [malllabiisc/EmbedKGQA#120]
Hello,

thank you for your valuable and interesting work!

I was wondering if there is any specific reason on why the knowledge base triplets have been inserted within the training data as questions that follow the same format as the original MetaQA dataset questions. Have those triplets been used during the training phase or should I refer only to those files that have the suffix "_old"? 

Best,
Andrei

**Comment by apoorvumang** [comment]
Hi, thanks for your interest

We found that adding the KG triplets as 'qa pairs' during QA training improves performance slightly (compared to using KG triplets just during KGE training). You can use both kinds of files, those with and without the suffix "_old", but the ones with QA pairs should be better performing.

**Comment by AndreiCComan** [comment]
Hello,

thank you for your prompt reply and for clarifying the matter.

Best,
Andrei
