### ISSUE TITLE
Question with "half KG" protocol

### ISSUE THREAD

**Issue by imhgchoi** [malllabiisc/EmbedKGQA#126]
Hi, first of all thank you for the awesome work you've done.

I'm relatively new to this domain, and was curious whether there is no fixed dataset for the "half KG" protocol in this domain?

Is it common to randomly select the set for ourselves? I did check out other repos and most of them were basically doing the same thing.

Sorry for this not being directly related to your work, but I couldn't find a proper place to ask the question.

Thank you in advance :)

**Comment by apoorvumang** [comment]
Yes, unfortunately there is no standard half KG (AFAIK)

**Comment by imhgchoi** [comment]
Many thanks :)
