### ISSUE TITLE
I download the ZIP but the data and pretrained_models are destroyed

### ISSUE THREAD

**Issue by Ironeie** [malllabiisc/EmbedKGQA#16]
the data and pretrained_models are both only 134 byte large and cannot be opened. Even though downloading the single file leads the same result. Do you know why it is, or can you give another way to download them? Thank you!

**Comment by mug2mag** [comment]
@Ironeie  @Vodkazy
Hi, I met the same problem. How did you solve it? Any reply will be very appreciated.
