### ISSUE TITLE
WebQuestionsSP code

### ISSUE THREAD

**Issue by ms0510k** [malllabiisc/EmbedKGQA#17]
When will the code for the 'WebQuestionsSP' dataset be updated?

Best Regards

**Comment by apoorvumang** [comment]
August 20, please keep track of this issue, thanks!

**Comment by xjtusedy** [comment]
Hope to see the code soon.

Best Regards!

**Comment by apoorvumang** [comment]
Please see the updated code and re-download data.zip and pretrained_models.zip
