### ISSUE TITLE
question_embedding  in your model

### ISSUE THREAD

**Issue by ToneLi** [malllabiisc/EmbedKGQA#2]
Why you use states[0] to compute the question embedding in a batch_size?  the size of states[0] is [batch_size,  embedding_dim], can you explain what's the meaning about states[0] ? I think question_embedding  should be state not state[0].  Can you help me?

    def getQuestionEmbedding(self, question_tokenized, attention_mask):
        roberta_last_hidden_states = self.roberta_model(question_tokenized, attention_mask=attention_mask)[0]
        states = roberta_last_hidden_states.transpose(1,0)#  torch.Size([64, 128, 768])
        cls_embedding = states[0]# torch.Size([128, 768])
        question_embedding = cls_embedding

**Comment by apoorvumang** [comment]
```
roberta_last_hidden_states = self.roberta_model(question_tokenized, attention_mask=attention_mask)[0]
```
This chooses the hidden states of the last layer of RoBERTa
```
states = roberta_last_hidden_states.transpose(1,0)#  torch.Size([64, 128, 768])
```
The dimensions are then transposed. So dimensions of state variable are (question length, batch size, embedding length).
```
cls_embedding = states[0]# torch.Size([128, 768])
question_embedding = cls_embedding
```
Now by using states[0], we take the embedding of the first token of each sentence, which is the CLS token. This is used as the question embedding.
I hope this explains your question. Thanks!

**Comment by ToneLi** [comment]
OK! Thanks!!
