### ISSUE TITLE
WebQuestionsSP Data

### ISSUE THREAD

**Issue by leewangon** [malllabiisc/EmbedKGQA#20]
Hello
Thanks for the material update.
However, it is not possible to decompress data.zip
I need 'WebQuestionsSP Data' in data.zip ​​for the experiment
Could you please check?

**Comment by apoorvumang** [comment]
I tried and it seems to work for me. It is in the directory` data/QA_data/WebQuestionsSP`. Could you share some more details about the error you are getting?

**Comment by apoorvumang** [comment]
I am assuming you were able to do it, hence closing this issue. Please reopen in case it didn't work.
