### ISSUE TITLE
 training command of Half KG in metaQA

### ISSUE THREAD

**Issue by ToneLi** [malllabiisc/EmbedKGQA#24]
can you supply the half metaQA training command? to get the entity embedding and relation embedding?

**Comment by apoorvumang** [comment]
Btw have you tried the pretrained embeddings for half KG? @ToneLi

**Comment by ToneLi** [comment]
No, do you have any advices? In your code, you used random embedding matrix,  
self.E = torch.nn.Embedding(len(d.entities), d1 * multiplier, padding_idx=0)

**Comment by apoorvumang** [comment]
If you run with flag kg_type=half, it automatically uses the pretrained embeddings

**Comment by ToneLi** [comment]
Thanks! How do you get the pretrained  entity embedding and relation embedding in half-KG in metaQA, I think you train the  half-KG by the same method with full KG,  am I right? If so, can you supply your paratemers, when training the half KG.

**Comment by apoorvumang** [comment]
Yes, it is trained in the same way, just using 50% of the edges. I will update with the command/parameters

**Comment by apoorvumang** [comment]
Also @ToneLi you may want to join a slack channel I created for live discussion via chat which might not be possible through github issues https://join.slack.com/t/embedkgqa/shared_invite/zt-h8el9pnl-AGqBiI2mZkkR~TCK5tBYzg

**Comment by ToneLi** [comment]
Thanks! Looking forward to your update!

**Comment by apoorvumang** [comment]
Please create a new issue if this isn't resolved. I am assuming this is about training the KG embedding for half KG?
