### ISSUE TITLE
I have successfully run the training code but unable to eval

### ISSUE THREAD

**Issue by Ironeie** [malllabiisc/EmbedKGQA#25]
I have successfully run the training code but it gave no print out. And I cannot run the code in eval mode since there's no eval function. Can you give the eval code? Thx

**Comment by apoorvumang** [comment]
Can you share what command you ran, and a screenshot of whatever you saw when you ran the command?

**Comment by Ironeie** [comment]
I ran the following code successfully
`python3 main.py --mode train --relation_dim 200 --hidden_dim 256 \
--gpu 3 --freeze 0 --batch_size 128 --validate_every 5 --hops 2 --lr 0.0005 --entdrop 0.1 --reldrop 0.2  --scoredrop 0.2 \
--decay 1.0 --model ComplEx --patience 5 --ls 0.0 --kg_type full`
But when I wanna get the test score and ran the following code:
`python3 main.py --mode eval --relation_dim 200 --hidden_dim 256 \
--gpu 3 --freeze 0 --batch_size 128 --validate_every 5 --hops 2 --lr 0.0005 --entdrop 0.1 --reldrop 0.2  --scoredrop 0.2 \
--decay 1.0 --model ComplEx --patience 5 --ls 0.0 --kg_type full`
It didin't work, and the error message was as follows:
`Traceback (most recent call last):
  File "main.py", line 361, in <module>
    embedding_dim=args.embedding_dim)
TypeError: eval() takes no keyword arguments`
which I think is because there's no eval function in main.py, is there?

**Comment by apoorvumang** [comment]
Yes, eval function isn't there, but eval happens when running the train command. What output did you get when you ran the train command?

**Comment by Ironeie** [comment]
Model has exceed patience. Saving best model and exiting.
And there isn't any score message

**Comment by Ironeie** [comment]
There IS validation accuracy, but no test accuracy

**Comment by apoorvumang** [comment]
Please see issue #14. Whenever validation accuracy increases it finds and prints the test accuracy. If this still doesn't work, please let me know.

**Comment by Ironeie** [comment]
Thank you for your reply, I've understood. When I train on KG-50, it can be shown normally. When I train on KG-Full, the best test score appears at the first epoch, therefore no test score is shown. For convenience, will you give the eval function and online QA code in the future?

**Comment by apoorvumang** [comment]
Yes, I'll create a new issue about having separate eval function. What do you mean by online QA code?

**Comment by Ironeie** [comment]
It means when inputing a question, output an answer, which realizes a question answering process.

**Comment by apoorvumang** [comment]
Got it. Can you please create a new issue with relevant title for this? I will close this one. It will be easier to resolve that way. Thanks.

**Comment by Ironeie** [comment]
All right
