### ISSUE TITLE
KG-EMbedding in MetaQA FULL-KG, HIT value is 1,  is it the right value?

### ISSUE THREAD

**Issue by ToneLi** [malllabiisc/EmbedKGQA#30]
Hi, Sorry to disturb you, I used the hyperparamaters you provided, why I get the HIT value is 1. It's the right result? (FULL KG metaQA)
![image](https://user-images.githubusercontent.com/33856565/92977258-19fa8200-f4bf-11ea-941a-517d7432b45e.png)

**Comment by apoorvumang** [comment]
Yes
