### ISSUE TITLE
The data link and the pretrained model link is unavailable

### ISSUE THREAD

**Issue by xwjim** [malllabiisc/EmbedKGQA#33]

**Comment by apoorvumang** [comment]
The file viewing policy got changed for my onedrive account, let me change the hosting

**Comment by apoorvumang** [comment]
Here's the link: https://drive.google.com/drive/folders/1RlqGBMo45lTmWz9MUPTq-0KcjSd3ujxc?usp=sharing

I will update this in readme as well
