### ISSUE TITLE
I get an error when i train on the WebQuestionsSP

### ISSUE THREAD

**Issue by xwjim** [malllabiisc/EmbedKGQA#35]
![Snipaste_2020-09-26_13-39-01](https://user-images.githubusercontent.com/11665562/94331288-e448b380-fffd-11ea-9dcb-4a1a0fe23fd7.png)
How can I fix the error. Thank you.

**Comment by apoorvumang** [comment]
Looks like an issue with installed packages in your conda environment. Maybe try reinstalling pyglet/ffmpeg?

I don't think this is directly related to the code present in this repository.

**Comment by xwjim** [comment]
Thank you

**Comment by gwliu213** [comment]
> ![Snipaste_2020-09-26_13-39-01](https://user-images.githubusercontent.com/11665562/94331288-e448b380-fffd-11ea-9dcb-4a1a0fe23fd7.png)
> How can I fix the error. Thank you.

Have you solve the problem? I got the same error.
