### ISSUE TITLE
How to run inference on new questions to get answer

### ISSUE THREAD

**Issue by Sharathmk99** [malllabiisc/EmbedKGQA#36]
Hi,
Thank you for amazing work.
I have trained MetaQA model for question answer. I got around `0.95` accuracy.

Now how can i run the inference on new questions?

Thank you.

**Comment by Sharathmk99** [comment]
Is this issue same as #27 ?

**Comment by apoorvumang** [comment]
Yes. However you can create a new dev dataset with single question and see the answer.

**Comment by Sharathmk99** [comment]
@apoorvumang Thank you.
