### ISSUE TITLE
How to get KG embeddings for custom KG

### ISSUE THREAD

**Issue by Sharathmk99** [malllabiisc/EmbedKGQA#37]
Hi,

We have build KG by extracting entities and relationship between entity from PDF documents. But out KG is not so big, we have around 5k nodes. 

Now we wanted to use EmbedKGQA source code to build Natural Language question on custom KG.

I have below 2 questions,
1. How do i convert my custom KG to embedings
2. Our KG is not big, do you think still i can use this method to answer natural language questions.

Thanks

**Comment by apoorvumang** [comment]
Hi

> Now we wanted to use EmbedKGQA source code to build Natural Language question on custom KG.

Not sure what you mean by building NL question. Do you mean QA dataset or QA answering system?

> 1. How do i convert my custom KG to embedings
> 2. Our KG is not big, do you think still i can use this method to answer natural language questions.

You can use libkge for getting embeddings.

Yes, you can still use this method

**Comment by Sharathmk99** [comment]
Hi @apoorvumang Thank you for your response.
We are trying to build QA answering system on our custom KG. For example if our KG is build on food recipes, user can ask How to cook rice? We wanted to get answer(which is KGs node) for this question.

Ok let me use libkge to build embeddings for my KG. Then I'll try to use this code base. I'll post here if I face any problems.

Thank you for the amazing work

**Comment by Sharathmk99** [comment]
Hi @apoorvumang  I can solve my use case as explained above using this code base right?

**Comment by apoorvumang** [comment]
Yes, you should be able to. In practice, it would first involve getting a KG + KGQA dataset for training, then training embeddings for the KG and then using this codebase. I closed the issue since it was not directly relevant to the codebase/paper. However, feel free to add comments here for any clarifications.

**Comment by Sharathmk99** [comment]
@apoorvumang Sure let me prepare KG and some KGQA dataset (may be around 500) and then I'll train embeddings. Thank you
