### ISSUE TITLE
Consultations on this paper

### ISSUE THREAD

**Issue by lzw429** [malllabiisc/EmbedKGQA#4]
Hi, I found this paper very enlightening, taking full advantage of the nature of knowledge graph embedding to complete multi-hop QA.
However, I have some doubts while reading the paper on ACL 2020.

How are the head entities in a natural language question get extracted, did this paper assumes that there is only one head entity in the question?

Thanks.

**Comment by IISCAditayTripathi** [comment]
We are glad that you found the paper helpful.

The paper makes the following assumptions:
1) The head entity in the question is known.
2) There is only one head entity in the question.

Please let us know if you something is unclear.
