### ISSUE TITLE
What are valid.txt and test.txt for KG data?

### ISSUE THREAD

**Issue by Ironeie** [malllabiisc/EmbedKGQA#42]
You've described that "Full dataset contains the original kb.txt as train.txt with duplicate triples removed", but what are valid.txt and test.txt at the same directory? Does KGE need to be verified and tested?

**Comment by apoorvumang** [comment]
They are there because most implementations require a valid.txt and test.txt file to be present along with train.txt . They contain a subset of the triples that are in train.txt.
