### ISSUE TITLE
How to find candidate answers

### ISSUE THREAD

**Issue by SRL94** [malllabiisc/EmbedKGQA#43]
Hi, thank you for sharing the source code. Could you please explain how does the model find all candidate answers in answer selection module? Thank you.

**Comment by ZuoZicheng** [comment]
Where did you find the answer selection module in source code ?

**Comment by SRL94** [comment]
I did not find it. I read it in the paper but it is not very clear to me.

**Comment by apoorvumang** [comment]
The answer selection module isn't explicitly written as such in the code. Without relation matching, it simply selects the highest scoring entity (which is being done in the current validation function)

With relation matching code is still not there yet, apologies for that.
