### ISSUE TITLE
Where's the definition of the function "hidden2rel" at line 125 in "KGQA/RoBERTa/model.py"?

### ISSUE THREAD

**Issue by Ironeie** [malllabiisc/EmbedKGQA#44]
You define a variable named "hidden2rel" at line 85, but you call the function "hidden2rel" at line 125 in function "applyNonLinear", where there's no definition of function "hidden2rel". Sorry for my poor coding level, can you tell me where's the definition of the function "hidden2rel" or what it means?

**Comment by Ironeie** [comment]
Sorry to disturb you, my problem has been solved

**Comment by ShaoZhangHao** [comment]
Hi, I have the same question in “hidden2rel” too，I don not know how and why the hidden state can be converted into the relation_embeddings. Is there any relationship between the relation and hidden state?
