### ISSUE TITLE
What dose "positive_head" mean in line 197 in "KGQA/LSTM/main.py"

### ISSUE THREAD

**Issue by Ironeie** [malllabiisc/EmbedKGQA#46]
`for i_batch, a in enumerate(loader):  `
`     model.zero_grad()  `
`     question = a[0].to(device)  `
`     sent_len = a[1].to(device)  `
 `    positive_head = a[2].to(device)  `
`     positive_tail = a[3].to(device) `
Since question represents the embedding of questions, sent_len represents the length of questions, positive_tail represents the lables(answers) of questions, what dose "positive_head" represent?

**Comment by apoorvumang** [comment]
positive_head is the entity present in the question. As followed by others, we assume entity linking to be 'perfect' ie. the model knows exactly which entity is there in the question. There is always exactly one entity.

**Comment by ShuangNYU** [comment]
> positive_head is the entity present in the question. As followed by others, we assume entity linking to be 'perfect' ie. the model knows exactly which entity is there in the question. There is always exactly one entity.

Is that true that `positive_tail` is a one-hot vector but only one position is '1'?

**Comment by Ironeie** [comment]
> > positive_head is the entity present in the question. As followed by others, we assume entity linking to be 'perfect' ie. the model knows exactly which entity is there in the question. There is always exactly one entity.
> 
> Is that true that `positive_tail` is a one-hot vector but only one position is '1'?



> > positive_head is the entity present in the question. As followed by others, we assume entity linking to be 'perfect' ie. the model knows exactly which entity is there in the question. There is always exactly one entity.
> 
> Is that true that `positive_tail` is a one-hot vector but only one position is '1'?

I tried to print the `positive_tail` and found that there are more than one position being '1', where I don't understand why they are.

**Comment by apoorvumang** [comment]
> > > positive_head is the entity present in the question. As followed by others, we assume entity linking to be 'perfect' ie. the model knows exactly which entity is there in the question. There is always exactly one entity.
> > 
> > 
> > Is that true that `positive_tail` is a one-hot vector but only one position is '1'?
> 
> I tried to print the `positive_tail` and found that there are more than one position being '1', where I don't understand why it is.

Multiple answers can be correct, so it's k-hot not 1-hot
