### ISSUE TITLE
Do you use RoBERTa for only fbwq but not MetaQA?

### ISSUE THREAD

**Issue by ShuangNYU** [malllabiisc/EmbedKGQA#47]
Hi,

When reading your code I found there is not a part in KGQA/LSTM that you load the transformer and use the pre-trained embeddings for sentences, as what you have done in KGQA/RoBERTa. Is that true, and why?

Best,
Shuang

**Comment by apoorvumang** [comment]
In LSTM, we don't use any text pretraining. This is because MetaQA has a large number of questions and the model can learn word embeddings from those questions.
