### ISSUE TITLE
The GPU used for training will be as slow as the CPU as long as there are other programs running?

### ISSUE THREAD

**Issue by Ironeie** [malllabiisc/EmbedKGQA#50]
The program only takes up more than 1G of GPU memory, which is very fast when run alone. However, if there are other programs running on this GPU, it will also take up more than 1G of GPU memory, but the speed will become as slow as the CPU, why? If there are other programs that use the GPU's other memory while the program running, the speed will suddenly become very, very slow (about a few hundredths of a percent). What's going on?

**Comment by apoorvumang** [comment]
I believe this might be a problem specific to your system/server. In any case, it would be helpful if you could give more info about your setup and problem.
