### ISSUE TITLE
Combining hop1 and hop2 training

### ISSUE THREAD

**Issue by Risho92** [malllabiisc/EmbedKGQA#53]
Thanks for the model code. I have a data set with approx. half of the samples are hop 1 and the other half hop 2. If I am to train an EmbedKGQA model, can I combine the hop 1 and hop 2 data and train a single model? Or do you recommend that I separate hop 1 and hop 2 data, and create separate models for hop 1 data and hop 2 data?

**Comment by apoorvumang** [comment]
You can train them together, we didn't report those results since the standard protocol is to report results separately.
