### ISSUE TITLE
how to create "E.npy"

### ISSUE THREAD

**Issue by ZuoZicheng** [malllabiisc/EmbedKGQA#55]
Hi, thank you for sharing the source code.  Could you please tell me how did you create the "E.npy" which located in " ../../pretrained_models/embeddings/ComplEx_MetaQA_half " ?

**Comment by mangonihao** [comment]
> Hi, thank you for sharing the source code. Could you please tell me how did you create the "E.npy" which located in " ../../pretrained_models/embeddings/ComplEx_MetaQA_half " ?

Hello, I meet the same problem as you. Do you know how to create "E.npy"?
