### ISSUE TITLE
File Id of pretrained_model.zip

### ISSUE THREAD

**Issue by Risho92** [malllabiisc/EmbedKGQA#57]
I am able to download pretrained_model.zip from the google drive into my personal system. Results look promising. Thanks for the model.
https://drive.google.com/drive/folders/1RlqGBMo45lTmWz9MUPTq-0KcjSd3ujxc?usp=sharing

I was trying to download pretrained_model.zip in our linux server, which does not have a UI. When I search online on how to download from google drive into a linux machine, answers look more or less like below. The issue with this is, I cannot use the folder id to download. But I need the file id. However much I tried, I am not able to get the file id for pretrained_model.zip. Can you please give the file id for this file from google drive?

wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=FILEID' -O FILENAME

**Comment by apoorvumang** [comment]
These are the the download links of individual zip files. Maybe these can help

https://drive.google.com/file/d/1uWaavrpKKllVSQ73TTuLWPc4aqVvrkpx/view?usp=sharing
https://drive.google.com/file/d/1Ly_3RR1CsYDafdvdfTG35NPIG-FLH-tz/view?usp=sharing

**Comment by Risho92** [comment]
Thank you!
