### ISSUE TITLE
Roberta vs SBert

### ISSUE THREAD

**Issue by Risho92** [malllabiisc/EmbedKGQA#58]
While working on other NLP tasks, we noticed that SBert performs better than Roberta in sentence level tasks. KGQA looks like a sentence level task. Have you tried SBert in the place of Roberta? What is your intuition on SBert's performance?

**Comment by apoorvumang** [comment]
We haven't tried it yet but SBert might be more suitable for getting question embedding.

**Comment by jishnujayakumar** [comment]
@Risho92, I have claimed this paper for  MLRC2020. I have tried using SBert and it performs better than RoBERTa.

**Comment by Risho92** [comment]
@jishnujayakumar thanks for trying that. I was also expecting SBert to perform better.

I was planning to write the code myself next month. If you have already done it, is it possible to share your repository?

**Comment by jishnujayakumar** [comment]
> @jishnujayakumar thanks for trying that. I was also expecting SBert to perform better.
> 
> I was planning to write the code myself next month. If you have already done it, is it possible to share your repository?

We will be making it live on Jan 29.

**Comment by Risho92** [comment]
Thanks @jishnujayakumar . This is so cool. Nice work!!!
