### ISSUE TITLE
RobertaModel

### ISSUE THREAD

**Issue by SRL94** [malllabiisc/EmbedKGQA#60]
Hi,
In `self.roberta_model = RobertaModel.from_pretrained(self.roberta_pretrained_weights)`, I does not find where the RobertaModel comes from.

**Comment by apoorvumang** [comment]
We use the huggingface transformers library

```
self.roberta_pretrained_weights = 'roberta-base'
self.roberta_model = RobertaModel.from_pretrained(self.roberta_pretrained_weights)
```

This way the weights for the model are automatically downloaded.
