### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by dinani65** [malllabiisc/EmbedKGQA#65]
Could you please explain how to solve this error?
When I run main.py in  ./KGQA/LSTM, I get the following error :

[Train file is  ../../data/QA_data/MetaQA/qa_train_2hop_half.txt
KG type is half
Model is ComplEx
Frozen: False
Traceback (most recent call last):
  File "main.py", line 345, in <module>
    bn_list=bn_list)
  File "main.py", line 172, in train
    model = RelationExtractor(embedding_dim=embedding_dim, hidden_dim=hidden_dim, vocab_size=len(word2ix), num_entities = len(idx2entity), relation_dim=relation_dim, pretrained_embeddings=embedding_matrix, freeze=freeze, device=device, entdrop = entdrop, reldrop = reldrop, scoredrop = scoredrop, l3_reg = l3_reg, model = model_name, ls = ls, w_matrix = w_matrix, bn_list=bn_list)
  File "/content/EmbedKGQA/KGQA/LSTM/model.py", line 94, in __init__
    self.bn_list[i][key] = torch.Tensor(value).to(device)
RuntimeError: CUDA error: invalid device ordinal](url)

**Comment by CaesarWZY** [comment]
hi, did u solve it? And by how? Did u change the code, please give me some details. Thanks a lot!

**Comment by riaz** [comment]
how was it closed?
