### ISSUE TITLE
How did you get pretrained_models webqsp.pt?

### ISSUE THREAD

**Issue by yaowang1112** [malllabiisc/EmbedKGQA#69]
I don't know how to get webqsp.pt when I do relation_matching.

**Comment by apoorvumang** [comment]
Are you referring to webqsp_scores_full_kg.pkl? This can be created as described in https://github.com/malllabiisc/EmbedKGQA/blob/master/KGQA/RoBERTa/README.md

**Comment by apoorvumang** [comment]
Yes sry that pretrained model is missed out, I will upload it and update you

**Comment by apoorvumang** [comment]
Please download the file using
```
curl http://transfer.sh/PbRHI/webqsp.pt -o webqsp.pt
```
And place it in the correct folder ``../../pretrained_models/relation_matching_models/webqsp.pt``

This is a temporary download and I will be moving this to pretrained_models.zip soon

**Comment by yaowang1112** [comment]
Thank you!

**Comment by yaowang1112** [comment]
I downloaded the file before, I am  curious about how to get webqsq.pt. Run which file can get webqsp.pt?

**Comment by apoorvumang** [comment]
This file: https://github.com/malllabiisc/EmbedKGQA/blob/master/KGQA/RoBERTa/pruning_main.py

You will have to edit it to save the checkpoint to the proper location with the proper name

**Comment by novice7** [comment]
Hi, I notice that it needs the files 'pruning_test.txt' and '/scratche/home/apoorv/mod_TuckER/data/fbwq_full_allrels/relations.dict' when I want to run the file: https://github.com/malllabiisc/EmbedKGQA/blob/master/KGQA/RoBERTa/pruning_main.py.

But I didn't find it in the data.zip(ps: the data.zip downloaded just 8 days ago)

Could you provide those files?

**Comment by dungtn** [comment]
@apoorvumang thank you for sharing, I notice that the `pruning_test.txt` is still missing from `data.zip`. Can you share the it? And the script to create `pruning_{train, test}.txt` if possible?

**Comment by apoorvumang** [comment]
@dungtn sure, can you please create a new issue regarding this? will be easier to track

**Comment by aravindarajanS** [comment]
@apoorvumang thanks for the code. please share pruning_test.txt and script for pruning file creation if possible. thanks
