### ISSUE TITLE
RelScore

### ISSUE THREAD

**Issue by Wangyinquan** [malllabiisc/EmbedKGQA#7]
Hello Dr. Apoorv,
According to your email, RelScore does not have a gradient. the scoring function S(r,q) has a gradient and that is trained separately. And RelScore is only used in valid and testing phase.  I wanna know  some details, do you mean S(r,q) induces a part of loss during training or it is trained after all training epoches?

**Comment by IISCAditayTripathi** [comment]
The EmbedKGQA model is trained separately and the relation scoring function  S(r,q) is trained separately. However, their score is combined at the evaluation time without any gradient backpropogation.
