### ISSUE TITLE
The way to get pruning_test.txt

### ISSUE THREAD

**Issue by novice7** [malllabiisc/EmbedKGQA#74]
The pruning_train.txt is in the data.zip, but there is lack of pruning_test.txt, I want to get this file by myself, but I find out that the  number of questions in pruning_train.txt is less than the  number of questions in the original training set.

What are the reasons for you to delete some questions

**Comment by apoorvumang** [comment]
In the WebQuestionsSP dataset, some questions do not have path annotations. So they cannot be used for relation matching training and have been removed.

**Comment by xxmeng20** [comment]
> pruning_train.txt位于data.zip中，但是缺少pruning_test.txt，我想自己获取该文件，但是我发现pruning_train.txt中的问题数量少于其中的问题数量。原始的训练集。
> 
> 您删除一些问题的原因是什么

**Comment by xxmeng20** [comment]
How to get pruning_test.txt ?

**Comment by apoorvumang** [comment]
@xxmeng20 you can just take a subset of train, maybe 5% of data points for validation. I don't think we should need test since this isn't actually a task we are reporting performance on.
