### ISSUE TITLE
In pruning_main.py best_mar12_3.pt should be saved as webqsp.pt?

### ISSUE THREAD

**Issue by anindyasdas** [malllabiisc/EmbedKGQA#75]
In EmbedKGQA/KGQA/RoBERTa/ there are two main programs. In pruning_main.py the commented out saved model is best_mar12_3.pt, is this same as webqsp.pt, ?
Should the Roberta model be saved as webqsp.pt?

**Comment by apoorvumang** [comment]
best_mar12_3.pt is same as webqsp.pt,
