### ISSUE TITLE
How to generate "webqsp_scores_full_kg.pkl"

### ISSUE THREAD

**Issue by ZuoZicheng** [malllabiisc/EmbedKGQA#76]
Thanks for sharing the source code . When I running the "relation_matching_eval.ipynb" , I found the score has already exists in "webqsp_scores_full_kg.pkl" , I want to know how to generate this dictionary (webqsp_scores_full_kg.pkl) ，and how the candidate score calculated .

**Comment by apoorvumang** [comment]
Please read https://github.com/malllabiisc/EmbedKGQA/tree/master/KGQA/RoBERTa#relation-matching-scoring
