### ISSUE TITLE
RuntimeError: stack expects each tensor to be equal size, but got [64] at entry 0 and [68] at entry 12

### ISSUE THREAD

**Issue by Yukyin** [malllabiisc/EmbedKGQA#78]
When I try to run main.py in Roberta, I met with the following problem. I  wanna know do someone else also had this problem？Here I screenshot the error.
![image](https://user-images.githubusercontent.com/43812253/115878911-b0424d80-a47b-11eb-9274-06d405cc2a71.png)
![image](https://user-images.githubusercontent.com/43812253/115878960-bafce280-a47b-11eb-9301-71c76324f30c.png)

**Comment by apoorvumang** [comment]
Can you please post the exact command you used?

**Comment by apoorvumang** [comment]
Closing assuming it was solved, please re-open if needed
