### ISSUE TITLE
How to get KG subset？

### ISSUE THREAD

**Issue by lxmm1999** [malllabiisc/EmbedKGQA#79]
Hi, I want to test your model on a new QA data set, but don't know how to filter a Freebase with 1.9 billion triples to get a subset that can answer the question.How do you get the subset of Freebase for WebQSP?

**Comment by apoorvumang** [comment]
We took 2-hop neighbourhood of all entities in WebQuestionsSP dataset, and then applied some more filtering. Unfortunately we do not have a script to recreate this subset right now.
