### ISSUE TITLE
What is the reason for preprocessing questions with additional tag 'NE'?

### ISSUE THREAD

**Issue by anindyasdas** [malllabiisc/EmbedKGQA#84]
what standard time is michigan? ---> what standard time is michigan NE
'what team is cristiano ronaldo play for NE'

`question = question_1+'NE'+question_2`

**Comment by apoorvumang** [comment]
can you please tell which code you are referring to?

**Comment by anindyasdas** [comment]
Hello,
The following module
/EmbedKGQA/blob/master/KGQA/RoBERTa/main.py

Line_no: 404

**Comment by apoorvumang** [comment]
it replaces the entity name with 'NE' (named entity) in the question. It helps slightly in performance, since entity information is not needed in question embedding. However it is not strictly necessary, you can just remove the '[]' brackets and proceed as well.
