### ISSUE TITLE
question embeddings

### ISSUE THREAD

**Issue by esulaiman** [malllabiisc/EmbedKGQA#88]
First, thank you for sharing the code. 

I have one question regarding generating the question embedding. I noticed that you used the CLS_embedding from the last hidden state. Why did you use the embedding of CLS rather than any other token?

Thank you in advance for answering my question.

**Comment by apoorvumang** [comment]
It's one of the common ways of getting sentence embeddings. SBERT (SentenceBert) is an alternative
