### ISSUE TITLE
pruning_test.txt

### ISSUE THREAD

**Issue by 2399240664** [malllabiisc/EmbedKGQA#92]
Can you tell me where the 'pruning_test.txt' file is?thank you

**Comment by apoorvumang** [comment]
Please download from here

[pruning_test.txt](https://github.com/malllabiisc/EmbedKGQA/files/6845510/pruning_test.txt)
[pruning_train.txt](https://github.com/malllabiisc/EmbedKGQA/files/6845511/pruning_train.txt)

**Comment by apoorvumang** [comment]
I have also added them to the repo
