### ISSUE TITLE
MetaQA KG embedding with data leakage 

### ISSUE THREAD

**Issue by AndDoIt** [malllabiisc/EmbedKGQA#94]
Thanks for your excellent work for multi-hop KGQA!
I find the KG dataset of MetaQA that you provided has serious data leakage among train.txt, valid.txt and test.txt, so I want to make sure whether your pre-trained embeddings are based on this dataset.

**Comment by apoorvumang** [comment]
I mixed up valid and test.txt in my last message - test.txt has triples from train.txt while valid.txt shouldn't have overlap.
